name: "[Test]"
description: Template to create an issue to descripe a test (-scenario)
title: "[Test]"
labels: [ testing ]
body:
  - type: markdown
    attributes:
      value: |
        For what Feature/Component is this Test. (Use # to select existing issues)
  - type: input
    attributes:
      label: Select Issue
      placeholder: "#"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Describe the expected behavior
  - type: textarea
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Testtype
      options:
        - Unittest
        - Integration
        - Performance





